name: theourgia
description: OS image made with blue-build
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40
modules:
  - type: files
    files:
      - usr: /usr
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
    remove:
      - firefox
      - firefox-langpacks
  - type: default-flatpaks
    notify: true
    system:
      install:
      remove:
  - type: signing
