---
name: theourgia
description: OS image made with blue-build
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40
modules:
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
  - type: default-flatpaks
    system:
      install:
        - com.brave.Browser
        - com.github.tchx84.Flatseal
        - io.mpv.Mpv
        - net.mullvad.MullvadBrowser
        - org.darktable.Darktable
        - org.gnome.Fractal
        - org.keepassxc.KeePassXC
        - org.telegram.desktop
        - org.torproject.torbrowser-launcher
  - type: brew
  - type: chezmoi
    repository: "ZharMeny"
  - type: signing
